### ISSUE TITLE
Improve Documentation certification to 100 %

### ISSUE THREAD

**Issue by ironjan** [ironjan/klausurtool-ror#183]
- [x] Fix Missing top-level module documentation comment. app/helpers/old_folder_instances_helper.rb#1
- [x] Fix Missing top-level class documentation comment. db/migrate/20160313124532_create_delayed_jobs.rb#1
- [x] Fix Missing top-level class documentation comment. config/application.rb#10
- [x] Fix Missing top-level module documentation comment. app/helpers/ausleihe_helper.rb#1
- [x] Fix Missing top-level class documentation comment. app/models/old_folder.rb#1
